# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        wget https://github.com/jepsen-io/maelstrom/releases/download/v0.2.3/maelstrom.tar.bz2
        mkdir maelstrom-java
        tar -xvf maelstrom.tar.bz2 -C maelstrom-java
        chmod a+rx maelstrom-java/maelstrom
        echo "MAELSTROM_BIN_PATH=$(realpath maelstrom-java)" > .env
        make dev-install
    - name: Run lint
      run: |
        pre-commit run --all-files
    - name: Test echo
      run: |
        sudo make test-echo
    - name: Test broadcast
      run: |
        sudo make test-broadcast
    - name: Test performance
      run: |
        sudo make test-performance
